name: KSInventory
main: ksinventory.KSInventory
version: 1.0

commands:
   inv:
      description: Used to suppress messages
      usage: /inv [help|quiet|q|verbose|v]
   retrySave:
      description: Used to retry a failed save
      usage: /retrySave [type] [worldName]
   retryGet:
      description: Used to retry a failed retrieve
      usage: /retryGet [type] [worldName]